CREATE TABLE DBVERSION
(
    DBVERSION INT         NOT NULL,
    CREATOR   VARCHAR(20) NOT NULL,
    CTS       TIMESTAMP,
    CONSTRAINT PK_DBVERSION PRIMARY KEY (DBVERSION)
);

INSERT INTO DBVERSION (DBVERSION, CREATOR) VALUES ( 1, 'createDB' );
