CREATE TABLE PERMISSION
(
    OBJECT_TYPE INT          NOT NULL,
    OBJECT_ID   INT          NOT NULL,
    PERM_GROUP  VARCHAR(100) NOT NULL,
    PERM_TYPE   INT          NOT NULL
);

CREATE INDEX IND_PERMISSION ON PERMISSION (OBJECT_TYPE, OBJECT_ID);
