CREATE TABLE SEQUENCE
(
    OID       INT                        NOT NULL AUTO_INCREMENT,
    SEQ_NAME  VARCHAR(50)                NOT NULL,
    SEQ_VALUE INT         DEFAULT 0      NOT NULL,
    DTS       DATETIME    DEFAULT NOW()  NOT NULL,
    CONSTRAINT PK_SEQUENCE PRIMARY KEY (OID)
);

CREATE UNIQUE INDEX IND_SEQUENCE_NME ON SEQUENCE(SEQ_NAME);

INSERT INTO SEQUENCE (SEQ_NAME) VALUES ('SEQ_X2_TEMPLATE_EXE_ID');
INSERT INTO SEQUENCE (SEQ_NAME) VALUES ('PAGE_ID');
