CREATE TABLE X2_JOB_START_TEMPLATE
(
    OID         INT                                    NOT NULL,
    TEMPLATE_ID INT                                    NOT NULL,
    START_MODE  ENUM( 'OK', 'ERROR', 'WAIT', 'RETRY' ) NOT NULL,
    VAR_MODE    ENUM( 'NONE', 'PRIORITY' )             NOT NULL,
    RUN_MODE    ENUM( 'FOREGROUND', 'BACKGROUND' )     NOT NULL,
    CONSTRAINT PK_X2_JOB_START_TEMPLATE PRIMARY KEY (OID),
    CONSTRAINT FK_X2_JOB_START_TEMPLATE_JID FOREIGN KEY (OID) REFERENCES X2_JOBLIST (OID),
    CONSTRAINT FK_X2_JOB_START_TEMPLATE_TID FOREIGN KEY (TEMPLATE_ID) REFERENCES X2_TEMPLATE (OID)
);
