CREATE TABLE X2_JOBLIST
(
    OID          INT           NOT NULL AUTO_INCREMENT,
    TEMPLATE_ID  INT           NOT NULL,
    JOB_TYPE     VARCHAR(20)   NOT NULL,
    JOB_NAME     VARCHAR(100)  NOT NULL,
    BREAKPOINT   INT,
    CONSTRAINT PK_X2_JOBLIST PRIMARY KEY (OID),
    CONSTRAINT FK_X2_JOBLIST_TEMPLATE_ID FOREIGN KEY (TEMPLATE_ID) REFERENCES X2_TEMPLATE (OID)
);
