CREATE TABLE X2_JOB_START
(
    OID           INT                                  NOT NULL AUTO_INCREMENT,
    JOBLIST_ID    INT                                  NOT NULL,
    TEMPLATE_ID   INT                                  NOT NULL,
    START_MODE    ENUM('manual','int','weekday','day') NOT NULL,
    SEKUNDEN      INT,
    DAY_OF_MONTH  INT,
    DAY_OF_WEEK   INT,
    START_HOUR    INT,
    START_MINUTES INT,
    VALIDFROM     DATE,
    VALIDUNTIL    DATE,
    CONSTRAINT PK_X2_JOB_START PRIMARY KEY (OID),
    CONSTRAINT FK_X2_JOB_START_JLID FOREIGN KEY (JOBLIST_ID) REFERENCES X2_JOBLIST (OID),
    CONSTRAINT FK_X2_JOB_START_TID FOREIGN KEY (TEMPLATE_ID) REFERENCES X2_TEMPLATE (OID),
    CONSTRAINT CO_X2_JOB_START_DOW CHECK (DAY_OF_WEEK BETWEEN 1 AND 10),
    CONSTRAINT CO_X2_JOB_START_H   CHECK (START_HOUR BETWEEN 0 AND 23),
    CONSTRAINT CO_X2_JOB_START_M   CHECK (START_MINUTES BETWEEN 0 AND 59)
);

