CREATE TABLE X2_JOB_BILLIT_ADAPTER
(
    OID            INT                      NOT NULL,
    INSTANCE       VARCHAR(255)             NOT NULL,
    MODUL          VARCHAR(255)             NOT NULL,
    PRODUCER       INT                      NOT NULL,
    MIN_MESSAGES   INT            DEFAULT 0 NOT NULL,
    BMQ_CHECK_TIME INT            DEFAULT 1 NOT NULL,
    CONSTRAINT PK_X2_JOB_BILLIT_ADAPTER PRIMARY KEY (OID),
    CONSTRAINT FK_X2_JOB_BILLIT_ADAPTER_OID FOREIGN KEY (OID) REFERENCES X2_JOBLIST (OID),
    CONSTRAINT FK_X2_JOB_BILLIT_ADAPTER_PRD FOREIGN KEY (PRODUCER) REFERENCES X2_JOBLIST (OID)
);
