CREATE TABLE X2_JOB_TREE
(   
    OID    INT NOT NULL,
    PARENT INT NOT NULL,
    CONSTRAINT FK_X2_JOB_TREE_OID FOREIGN KEY (OID) REFERENCES X2_JOBLIST (OID),
    CONSTRAINT FK_X2_JOB_TREE_PARENT FOREIGN KEY (PARENT) REFERENCES X2_JOBLIST (OID)
);
