CREATE TABLE X2_LOGFILE
(
    OID             INT(11)       NOT NULL,
    DATA            LONGBLOB,
    FILENAME        VARCHAR(255),
    TEMPLATE_EXE_ID INT,
    PRIMARY KEY (OID),
    CONSTRAINT FK_X2_LOGFILE_OID FOREIGN KEY (OID) REFERENCES X2_WORKLIST (OID)
);

CREATE INDEX IND_X2_LOGFILE_FILENAME ON X2_LOGFILE (FILENAME);
CREATE INDEX IND_X2_LOGFILE_TEMPLATE_EXE_ID ON X2_LOGFILE (TEMPLATE_EXE_ID);
