CREATE TABLE X2_TEMPLATE_TREE
(
    OID    INT       NOT NULL,
    PARENT INT       NOT NULL,
    VGRAD  INT       NOT NULL,
    CONSTRAINT FK_X2_TEMPLATE_TREE_OID    FOREIGN KEY (OID)    REFERENCES X2_TEMPLATE (OID),
    CONSTRAINT FK_X2_TEMPLATE_TREE_PARENT FOREIGN KEY (PARENT) REFERENCES X2_TEMPLATE (OID)
);

CREATE INDEX ID_X2_TEMPLATE_TREE_OID ON X2_TEMPLATE_TREE (OID);
