CREATE TABLE X2_TEMPLATE_NOTIFIER
(
    OID         INT          NOT NULL AUTO_INCREMENT,
    TEMPLATE_ID INT          NOT NULL,
    STATE       INT          NOT NULL,
    RECIPIENT   VARCHAR(100) NOT NULL,
    CONSTRAINT PK_X2_TEMPLATE_NOTIFIER PRIMARY KEY (OID),
    CONSTRAINT FK_X2_TEMPLATE_NOTIFIER_TID FOREIGN KEY (TEMPLATE_ID) REFERENCES X2_TEMPLATE (OID)
);

CREATE UNIQUE INDEX UK_X2_TEMPLATE_NOTIFIER ON X2_TEMPLATE_NOTIFIER (TEMPLATE_ID, STATE, RECIPIENT);
