CREATE TABLE X2_TEMPLATE
(
    OID               INT                        NOT NULL AUTO_INCREMENT,
    OBJECT_TYPE       ENUM( 'G', 'T')            NOT NULL,
    OBJECT_NAME       VARCHAR(100)               NOT NULL,
    STATE             INT             DEFAULT 0  NOT NULL,
    RUN_STATE         INT,
    EXE_STATE         INT,
    LAST_RUN          DATETIME,
    LAST_DURATION     INT,
    NEXT_START_TIME   DATETIME,
    ACTUAL_START_TIME DATETIME,
    CONSTRAINT PK_X2_TEMPLATE PRIMARY KEY (OID)
);

CREATE INDEX IND_X2_TEMPLATE_OBJECT_TYPE ON X2_TEMPLATE (OBJECT_TYPE);
