CREATE TABLE X2_VIREW_OPTION
(
    X2_USER    VARCHAR(50)  NOT NULL,
    VIEW_NAME  VARCHAR(100) NOT NULL,
    VIEW_VALUE INT
);

CREATE UNIQUE INDEX UQ_X2_VIREW_OPTION ON X2_VIREW_OPTION (X2_USER, VIEW_NAME);
