CREATE TABLE X2_WORK_VARIABLE
(
    TEMPLATE_EXE_ID INT          NOT NULL,
    VAR_NAME        VARCHAR(50)  NOT NULL,
    VAR_VALUE       VARCHAR(255) NOT NULL,
    CONSTRAINT PK_X2_WORK_VARIABLE PRIMARY KEY (TEMPLATE_EXE_ID, VAR_NAME)
);
