CREATE TABLE X2_WORK_TREE
(
    OID             INT NOT NULL,
    PARENT          INT NOT NULL,
    TEMPLATE_EXE_ID INT NOT NULL,
    CONSTRAINT FK_X2_WORK_TREE_OID FOREIGN KEY (OID) REFERENCES X2_WORKLIST (OID),
    CONSTRAINT FK_X2_WORK_TREE_PARENT FOREIGN KEY (PARENT) REFERENCES X2_WORKLIST (OID)
);

CREATE INDEX IND_X2_WORK_TREE_TEMPLATE_EXE_ID ON X2_WORK_TREE (TEMPLATE_EXE_ID);
